Repository RedHatQE/qe-metrics, pull requests merged in 2024-03, with the labels that each got.

#35 Update in-solidarity to ignore `tests/unittests/utils.py`
  .github/in-solidarity.yml
Labels: verified, size/XS, can-be-merged, branch-main, approved-rnetser

#39 [MSINTEROP-824] Add documentation for credential configuration
  README.md
Labels: verified, size/M, can-be-merged, branch-main, approved-myakove

#42 [MSINTEROP-826] Create Jira class
  README.md
  qe_metrics/cli.py
  qe_metrics/libs/jira.py
Labels: verified, size/M, can-be-merged, branch-main, approved-myakove

#53 Add renovate.json
  renovate.json
Labels: verified, size/XS, can-be-merged, branch-main, approved-myakove

#47 [MSINTEROP-720] Add functionality to parse products file
  README.md
  qe_metrics/cli.py
  qe_metrics/libs/database.py
  qe_metrics/manifests/products.example.yaml
  qe_metrics/utils/general.py
  tests/unittests/conftest.py
  tests/unittests/libs/test_database.py
  tests/unittests/utils/test_general.py
Labels: verified, size/L, can-be-merged, branch-main, approved-myakove

#61 Update `.gitignore` to ignore `.vscode/`
  .gitignore
Labels: verified, size/XS, can-be-merged, branch-main, approved-myakove

#63 [MSINTEROP-824] Add database schema documentation
  README.md
  docs/img/db-schema.png
Labels: verified, size/XS, can-be-merged, branch-main, approved-myakove

#67 Add FCN plugin to flake8
  .flake8
  qe_metrics/libs/database.py
  qe_metrics/libs/jira.py
  tests/unittests/utils/test_general.py
Labels: verified, size/S, can-be-merged, branch-main, approved-myakove

#65 Removing support for python 3.12. ORM only supports up to 3.11
  container/Dockerfile
  poetry.lock
  pyproject.toml
  tox.ini
Labels: verified, size/L, can-be-merged, branch-main, approved-myakove
