Repository RedHatQE/qe-metrics, pull requests merged in 2024-04, with the labels that each got.

#59 [MSINTEROP-722] Populate qe-metrics database with issues from provided Jira queries
  qe_metrics/cli.py
  qe_metrics/libs/database.py
  qe_metrics/libs/database_mapping.py
  qe_metrics/libs/jira.py
  qe_metrics/utils/issue_utils.py
  qe_metrics/utils/product_utils.py
  tests/unittests/conftest.py
  tests/unittests/libs/test_database.py
  tests/unittests/libs/test_database_mapping.py
  tests/unittests/libs/test_jira.py
  tests/unittests/utils/test_general.py
  tests/unittests/utils/test_issue_utils.py
  tests/unittests/utils/test_product_utils.py
Labels: verified, size/XXL, can-be-merged, branch-main, commented-rnetser, approved-myakove, approved-rnetser

#73 Update db schema photo to remove `date_record_modified` from `jiraissues`
  docs/img/db-schema.png
Labels: verified, size/XS, can-be-merged, branch-main, approved-myakove

#78 Add issue_type column to DB and don't force only bugs to be added to DB
  docs/img/db-schema.png
  qe_metrics/libs/database_mapping.py
  qe_metrics/utils/issue_utils.py
  tests/unittests/libs/test_database_mapping.py
  tests/unittests/utils/test_issue_utils.py
Labels: verified, size/XS, can-be-merged, branch-main, approved-myakove, approved-rnetser

#75 [MSINTEROP-723] Implement a data retention policy
  README.md
  poetry.lock
  pyproject.toml
  qe_metrics/cli.py
  qe_metrics/utils/issue_utils.py
  qe_metrics/utils/product_utils.py
  tests/unittests/conftest.py
  tests/unittests/utils/test_issue_utils.py
  tests/unittests/utils/test_product_utils.py
Labels: verified, size/L, can-be-merged, branch-main, approved-myakove, approved-rnetser

#84 Use `function_runner_with_pdb`, this will enter `pdb` when `--pdb` passed
  poetry.lock
  pyproject.toml
  qe_metrics/cli.py
Labels: verified, size/M, can-be-merged, branch-main, approved-rnetser

#88 send status to slack on error/success
  README.md
  poetry.lock
  pyproject.toml
  qe_metrics/cli.py
  qe_metrics/utils/issue_utils.py
  tox.ini
Labels: verified, size/M, can-be-merged, branch-main, approved-rnetser, approved-calebevans

#86 Move unittests to tests
  tests/conftest.py
  tests/test_libs/__init__.py
  tests/test_libs/test_database_mapping.py
  tests/test_libs/test_jira.py
  tests/test_utils/__init__.py
  tests/test_utils/test_general.py
  tests/test_utils/test_issue_utils.py
  tests/test_utils/test_product_utils.py
  tests/unittests/utils/__init__.py
  tox.ini
Labels: verified, size/XS, can-be-merged, branch-main, approved-calebevans

#91 Run in background and support call update from url
  .flake8
  .pre-commit-config.yaml
  README.md
  poetry.lock
  pyproject.toml
  qe_metrics/cli.py
  qe_metrics/utils/entrypoint.py
  qe_metrics/utils/general.py
  qe_metrics/utils/issue_utils.py
  renovate.json
Labels: verified, size/XL, can-be-merged, branch-main, approved-rnetser, approved-calebevans

#97 Use qe metrics products config
  .pre-commit-config.yaml
  qe_metrics/cli.py
  qe_metrics/utils/entrypoint.py
  qe_metrics/utils/general.py
  qe_metrics/utils/product_utils.py
  tests/test_utils/test_product_utils.py
Labels: verified, size/M, can-be-merged, branch-main, approved-calebevans

#101 Get products dict in one function
  qe_metrics/utils/entrypoint.py
  qe_metrics/utils/product_utils.py
  tests/test_utils/test_product_utils.py
Labels: verified, size/S, can-be-merged, branch-main, approved-calebevans

#103 Replace Pony ORM with Sqlalchemy
  README.md
  poetry.lock
  pyproject.toml
  qe_metrics/libs/database.py
  qe_metrics/libs/database_mapping.py
  qe_metrics/utils/entrypoint.py
  qe_metrics/utils/issue_utils.py
  qe_metrics/utils/product_utils.py
  tests/conftest.py
  tests/test_libs/test_database_mapping.py
  tests/test_utils/test_issue_utils.py
  tests/test_utils/test_product_utils.py
  tox.ini
Labels: size/XXL, has-conflicts, branch-main

#108 Get product configs from split url config files
  poetry.lock
  pyproject.toml
  qe_metrics/cli.py
  qe_metrics/utils/entrypoint.py
  qe_metrics/utils/product_utils.py
Labels: verified, size/M, can-be-merged, branch-main, commented-calebevans, approved-calebevans, commented-myakove

#105 Allow product to only provide one of the queries
  qe_metrics/utils/general.py
  tests/test_utils/test_general.py
Labels: verified, size/S, can-be-merged, branch-main, approved-myakove

#111 Add files for release, fix tox
  .release-it.json
  VERSION
  poetry.lock
  pyproject.toml
  qe_metrics/libs/jira.py
  qe_metrics/utils/general.py
  tox.ini
Labels: verified, size/L, can-be-merged, branch-main, approved-rnetser, approved-calebevans

#119 Update base image and remove unneeded package installations
  container/Dockerfile
Labels: verified, size/XS, needs-rebase, can-be-merged, branch-main, approved-myakove

#122 Add a route for health checks
  qe_metrics/cli.py
Labels: verified, size/XS, can-be-merged, branch-main, approved-myakove, JIRA:None
