Repository RedHatQE/qe-metrics, pull requests merged in 2024-02, with the labels that each got.

#2 [QC-40] Setup the repository
  .flake8
  .github/in-solidarity.yml
  .github/workflows/close-stale-issues.yml
  .gitignore
  .markdownlint.json
  .pre-commit-config.yaml
  LICENSE
  Makefile
  OWNERS
  README.md
  container/Dockerfile
  poetry.lock
  pyproject.toml
  tox.ini
Labels: verified, size/XXL, branch-main, approved-myakove, approved-rnetser

#13 [MSINTEROP-728] Start qe-metrics CLI
  container/Dockerfile
  poetry.lock
  pyproject.toml
  qe_metrics/__init__.py
  qe_metrics/cli.py
  qe_metrics/libs/__init__.py
  qe_metrics/libs/database.py
  qe_metrics/libs/jira.py
  qe_metrics/manifests/creds.example.yaml
  qe_metrics/manifests/services.example.yaml
Labels: verified, size/XL, can-be-merged, branch-main, approved-myakove

#24 Use `pyproject.toml` and `pytest.ini` to configure `pytest-cov`
  .gitignore
  .pre-commit-config.yaml
  pyproject.toml
  pytest.ini
  tox.ini
Labels: verified, size/S, can-be-merged, branch-main, approved-rnetser
